FROM python:3.9-slim

RUN apt-get update && apt-get install -y curl && \
    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" && \
    chmod +x kubectl && mv kubectl /usr/local/bin/

RUN pip install flask

COPY remediation-service.py /app/remediation-service.py

WORKDIR /app

CMD ["python3", "remediation-service.py"]
